site_name: Mare Nostrum
theme:
  name: material
  language: en
  features:
    - navigation.instant
    - navigation.tracking
    - search.suggest
    - search.highlight
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: orange
      accent: orange
      toggle:
        icon: material/brightness-7
        name: Ciemny motyw
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: orange
      accent: orange
      toggle:
        icon: material/brightness-4
        name: Jasny motyw

nav:
  - Introduction: index.md