site_name: Mare Nostrum LAB
theme:
  name: material
  language: en
  features:
    - navigation.instant
    - navigation.tracking
    - search.suggest
    - search.highlight
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: orange
      accent: orange
      toggle:
        icon: material/brightness-7
        name: Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: orange
      accent: orange
      toggle:
        icon: material/brightness-4
        name: Light mode

nav:
  - Quick Start: index.md
  - Account Management: account-management.md
  - Creating a New Record in the Thesaurus - Cradle: cradle.md
  - Mare Nostrum Thesaurus - Management: mare-nostrum-thesaurus.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences